### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by manusis** [jesseditson/winston-sns#1]
# When I use it the way mentioned in docs

var winston = require('winston');
require('winston-sns').SNS;
winston.add(winston.transports.SNS, {aws_key: nconf.get("aws_key") , aws_secret: nconf.get("aws_secret"), level: 'error', subject: "Error Report", subscriber: nconf.get("aws_account"), topic_arn: nconf.get("aws_topic_arn")});

 var instance = created ? transport : (new (transport)(options));
                                        ^
TypeError: undefined is not a function
    at Logger.add (/Users/me/projects/abc/app/node_modules/winston/lib/winston/logger.js:425:41);
# 

When I use it like this

winston.add(require('winston-sns').SNS, {aws_key: nconf.get("aws_key") , aws_secret: nconf.get("aws_secret"), level: 'error', subject: "Error Report", subscriber: nconf.get("aws_account"), topic_arn: nconf.get("aws_topic_arn")});

../node_modules/winston-sns/node_modules/awssum/lib/amazon/amazon.js:66
        throw MARK + 'accessKeyID is required';
                   ^
amazon: accessKeyID is required

**Comment by vijaybarnwal** [comment]
I am unable to use winston-sns module If I use this I didnt found any error but I didnt got any mail also.

Please help me whats the issue?

var winston = require('winston');
var nconf = require("nconf");
var env = nconf.get("environment");
require('winston-sns').SNS;
var logger = null;
if (env != "dev") {
    logger = new (winston.Logger)({
        transports: [
            new ( winston.transports.SNS)({aws_key: "aws_key",aws_secret: "aws_secret",subscriber:'subscriberId', topic_arn: 'arn_topic',subject: 'Error Report',level:'error',handleExceptions: true}),
            new (winston.transports.Console)({ json: false, timestamp: true, handleExceptions: true }),
            new (winston.transports.File)({ filename: "/var/log/mystore-debug.log", json: false, timestamp: true, level: 'error',handleExceptions: true})
        ],
        exceptionHandlers: [
            new ( winston.transports.SNS)({aws_key: "aws_key",aws_secret: "aws_secret",subscriber:'subscriberId', topic_arn: 'topic_arn',subject: 'uncaughtException',level:'error',handleExceptions: true}),
            new (winston.transports.Console)({ json: false, timestamp: true}),
            new (winston.transports.File)({filename: "/var/log/mystore-exceptions.log", json: false, timestamp: true, level: 'error'})
        ],
        exitOnError: false
    });
}

here aws_key, aws_secret, arn_topic are valid values from aws account.

Please help me I had stuck on this issue.

Thanks,
Vijay

**Comment by jesseditson** [comment]
Hey guys, looks like this project is back up - closing this issue as the code was re-written.
