### ISSUE TITLE
silent parameter like some of the standard transports

### ISSUE THREAD

**Issue by daraghking** [jesseditson/winston-sns#4]
Add a silent parameter (default: false) that works the same way as it does in the standard transports e.g. Console.

I think the implementation will be easy.

In winston-sns.coffee
Add 'silent': false to the end of optional object
Add if (this.silent) { return callback(null, true); }  I don't use coffeescript so I dont know the best coffee way to write this.

I would be happy to figure out the coffee way and create a pull request or if you want to quickly do it that is fine with me to ;). I just want to see if it is something you would consider adding if I do it.

**Comment by MattCBowman** [comment]
@daraghking - this sounds like a good idea. I'll see if I can get some time in the next week to add it. Thanks!

**Comment by MattCBowman** [comment]
solved in #5
